#!/bin/bash
# Download KEYDB.cfg and backup if already here.

KEYDB_DIR="/etc/xdg/aacs"
KEYDB_FILENAME="KEYDB.cfg"
RANDOM12=`seq 1 2 | sort -R | head -n 1`
KEYDB_URL1="http://vlc-aacs.whoknowsmy.name/files"
KEYDB_URL2="http://vlc-bluray.whoknowsmy.name/files"
KEYDB_URL=`eval "echo \\${KEYDB_URL${RANDOM12}}"`

echo -ne "\n *************************************\n"
if [ ! -f $KEYDB_DIR/$KEYDB_FILENAME ]; then
	mkdir -p $KEYDB_DIR
else
	echo -ne " Backup $KEYDB_DIR/$KEYDB_FILENAME to $KEYDB_DIR/$KEYDB_FILENAME.back\n"
	cp $KEYDB_DIR/$KEYDB_FILENAME $KEYDB_DIR/$KEYDB_FILENAME.back
	echo -ne " *************************************\n"
fi

echo -ne " Downloading KEYDB.cfg...\n"
wget $KEYDB_URL/$KEYDB_FILENAME -O $KEYDB_DIR/$KEYDB_FILENAME

echo -ne " *************************************\n"

